### ISSUE TITLE
Problem =/

### ISSUE THREAD

**Issue by guztavoalves** [TheExtensionLab/Documentation#1]
Unzipped the files on my FTP, cleaned the cache and configuration options appeared less to: Magento Admin> Sytem> System Configuration> TheExtensionLab> Status Colors This menu does not appear.

In order page lines are not colored, even with the plugin enabled.

**Comment by JamesAnelay** [comment]
Hello @guztavoalves,
Do you see TheExtensionLab_StatusColors under System Configuration > Advanced > Advanced?

Join me in the chat here https://gitter.im/TheExtensionLab/StatusColors it's a little easier to communicate in there in a private message then it is on here.
- James

**Comment by JamesAnelay** [comment]
I have now corrected the incorrect paths in the documentation. e.g Admin> Sytem> System Configuration> TheExtensionLab> Status Colors was incorrect. Let me know in that chat if you still have issues using those paths.
