### ISSUE TITLE
Megamenu instructions don't make sense

### ISSUE THREAD

**Issue by lfolco** [TheExtensionLab/Documentation#4]
I am trying to figure out what has 24 columns in these instructions:

For example, what is a section? Is it a column on the menu?

![image](https://cloud.githubusercontent.com/assets/1709329/10105182/5996c3f4-637b-11e5-900d-84a519103d00.png)

Maybe a step-by-step instruction on how to create the menu in the screenshot could help? As it is I can't figure out how to create megamenu without doing a lot of trial and error.

**Comment by JamesAnelay** [comment]
So in those instructions the bit that has 24 columns is the full width promo image.

The Menu uses a grid system so the top full width promo image is 100% or in terms of the grid all 24 of 24 columns.

A third would be 8 of 24 and a half 12 of 24.

But I agree needs work. Prehaps breaking down into basics to begin with.

**Comment by JamesAnelay** [comment]
I've now re-worked this page starting with what a section is and I think providing a much clearer image for the columns example - http://docs.theextensionlab.com/mega-menu/create-a-dropdown.html.

I've also gone ahead and re-worded "Section X Columns" To "Section X Width" which is it's true purpose. And provided a hint next to each value e.g "12 of 24 (50%)". I hope that makes things a little clearer.

<img width="578" alt="screen shot 2015-09-28 at 12 42 14" src="https://cloud.githubusercontent.com/assets/7728332/10134735/f3850e92-65df-11e5-8013-09b51c369db3.png">

Does that make it a little eaiser to follow @lfolco?
Thanks again - James
